server:
  listenAddress: "localhost"
  port: 4000
  debug: true
dbSync:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "v8hlDV0yMAHHlIurYupj"
  database: "cexplorer"
  maxConnections: 10
network: "testnet"
tokenRegistryUrl: "https://tokens.cardano.org/metadata"
